import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { localeLayoutData } from "../locales/getData";
import Footer from "@/components/Footer";

const splineSans = Spline_Sans({
  variable: "--font-spline",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Homepage - Next.js CMS",
  description: "Generated by create next app",
};

async function layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const data = localeLayoutData[lang as keyof typeof localeLayoutData];
  return (
    <html lang={lang}>
      <body
        className={`${splineSans.className} antialiased  bg-background-dark font-display text-white `}
      >
        <NavBar lang={lang} />
        {children}
        <Footer footer={data.footer} lang={lang} />
      </body>
    </html>
  );
}

export default layout;
