import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import { localeLayoutData } from "../locales/getData";
import Footer from "@/components/Footer";

const splineSans = Spline_Sans({
  variable: "--font-spline",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Homepage - Next.js CMS",
  description: "Generated by create next app",
  keywords: [
    "nexuscms",
    "cms",
    "content management system",
    "nextjs cms",
    "nextjs cms",
  ],
  applicationName: "NexuxCMS",
  authors: [{ name: "BuildCode Dev", url: "https://buildkube.com" }],
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    title: "NexuxCMS — Contact",
    description: "A short CMS description",
    url: "https://nexuscms.com/",
    siteName: "NexuxCMS",
    images: [
      {
        url: "https://nexuscms.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "My App preview image",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "NexuxCMS — Contact",
    description: "A short CMS description",
    images: ["https://nexuscms.com/twitter-image.jpg"],
    site: "@nexuscms",
  },
};

async function layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const data = localeLayoutData[lang as keyof typeof localeLayoutData];
  return (
    <html lang={lang}>
      <body
        className={`${splineSans.className} antialiased bg-background-dark font-display text-white `}
      >
        <NavBar lang={lang} />
        {children}
        <Footer footer={data.footer} lang={lang} />
      </body>
    </html>
  );
}

export default layout;
